# Generated by Django 4.0.5 on 2022-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
